texture(test)
texture(player)
texture(rock)
texture(rock_icon)
texture(rock_albedo)
texture(coal_icon)
texture(coal_albedo)

texture(particle)
texture(particle_color_map_red)
texture(particle_color_map_blue)
texture(particle_color_map_white)
